### ISSUE TITLE
BUG - [fivetran/quickbooks dbt package results in inaccurate Balance Statement and P&L Tables]

### ISSUE THREAD

**Issue by jon-lonski** [fivetran/dbt_quickbooks#24] opened 2021-09-02 18:13 UTC
**Are you a current Fivetran customer?** 

Hi, My name is Jonathan Lonski and I am a data scientist at Furey Financial Services

**Describe the bug**

The data within the balance sheet and profit_and_loss tables that result from the fivetran/quickbooks dbt package does not match the data I see in the quickbooks online reports for the given periods.

**Steps to reproduce**
1. I use the Cheeky connector in my fivetran account to pull my data from QBO and push into BigQuery.
2. I use dbt Cloud to install the fivetran/quickbooks package, and on the command line I run "dbt deps" and then "dbt run" (project and package code to follow, disabling variables for tables that do not exist for the client's schema)
3. I compare the values in the resulting 'quickbooks__balance_sheet' and 'quickbooks__profit_and_loss' to the reports for respective periods directly in quickbooks online

**Expected behavior**

I expect the values to match for all of the accounts but they only match for about half of them. Seems like the issues may be volume dependent - for example, loan, clearing account, deferred revenue and the depreciation balances that only have 0-1 adjustments each month are captured correctly, however the credit card, checking account, and inventory balances are inaccurate.

**Project variables configuration**

name: 'fivetran_utils2'
version: '0.2.4'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

require-dbt-version: ">=0.20.0"

vars:
  quickbooks_database: tulaarchive5ttest
  quickbooks_schema: cheeky
  using_credit_memo:    false         #disable if you don't have credit memos in Quickbooks
  using_department:     false         #disable if you don't have departments in Quickbooks
  using_estimate:       false         #disable if you don't have estimates in Quickbooks
  using_invoice:        false         #disable if you don't have invoices in Quickbooks
  using_invoice_bundle: false         #disable if you don't have invoice bundles in Quickbooks
  using_payment:        false         #disable if you don't have payments in Quickbooks
**Package Version**
packages:
  - package: fivetran/quickbooks
    version: 0.3.0

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment] 2021-09-09 21:47
Link to the ongoing [dbt slack](https://getdbt.slack.com/archives/C01D1R2JLLA/p1630516303049100) conversation.

**Comment by fivetran-joemarkiewicz** [comment] 2021-09-13 18:40
Closing this ticket as the result of the issue most likely is the cause of a connector sync error. A ticket has been opened to help resolve this on the connector side. 

Feel free to open this ticket or a new one if you have any other questions. Thanks!

**Closed by fivetran-joemarkiewicz** 2021-09-13 18:40 UTC
Labels: bug
