### ISSUE TITLE
[Bug] Can't install package due to external connection exception

### ISSUE THREAD

**Issue by antoniofranciscoandrade** [fivetran/dbt_quickbooks#90] opened 2023-05-13 03:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Running `dbt deps` returns the following error:

```
03:33:17  Running with dbt=1.5.0
03:33:24  Encountered an error:
External connection exception occurred: Unterminated string starting at: line 1 column 10213 (char 10212)
```

My packages.yml file contains the following:

```
packages:
  - package: fivetran/quickbooks
    version: 0.9.0
```

### Relevant error log or model output

```shell
03:33:17  Running with dbt=1.5.0
03:33:24  Encountered an error:
External connection exception occurred: Unterminated string starting at: line 1 column 10213 (char 10212)
```

### Expected behavior

Package should be able to install

### dbt Project configurations

My dbt_project.yml is the following:

```
name: "transformations"
version: "1.0.0"
config-version: 2

vars:
  quickbooks_union_schemas: ["schema_a", "schema_b"]

profile: "transformations"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  transformations:
    example:
      +materialized: view
```

### Package versions
```
packages:
  - package: fivetran/quickbooks
    version: 0.9.0
```
### What database are you using dbt with?

postgres

### dbt Version

1.5.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2023-05-15 16:07
Hi @antoniofranciscoandrade thanks for opening this issue.

I have seen errors similar to this before. I believe this is caused by one of two things:
- There may have been a dbt hub or github outage at the time of attempting this installation. This could result in the error you are seeing. Are you able to try again (noting no GitHub outage) and see if this works?
- Your company or organization has a proxy in place that does not allow the installation of external packages.

Most often the type of issue you are seeing is caused by the second point above. Do you know if your company uses a proxy or firewall to restrict external package installations?

Additionally, I was able to recently install this version of the package without error.

**Comment by antoniofranciscoandrade** [comment] 2023-05-15 16:23
The issue is odd because I'm not under any proxy and most packages I've tried to install give the same error. I've managed to the install [dlh_quickbooks](https://hub.getdbt.com/datalakehouse/dlh_quickbooks/latest/) though, so doesn't seem like it is a dbt hub outage either.

Any idea on what's the cause?

**Comment by fivetran-joemarkiewicz** [comment] 2023-05-15 16:28
That is strange indeed. What other packages do you have trouble installing?

**Comment by antoniofranciscoandrade** [comment] 2023-05-15 16:32
So far I've had success with datalakehouse/dlh_quickbooks and trouble with: 

fivetran/amazon_ads
Fleetio/dbt_segment
brooklyn-data/dbt_artifacts
calogica/dbt_date
cerebriumai/airbyte_facebook_ads
data-mie/dbt_profiler
cerebriumai/airbyte_facebook_ads

**Comment by antoniofranciscoandrade** [comment] 2023-05-15 22:05
Managed to get it working by downgrading my python version from 3.9.6 to 3.7.13. Seems like the problem was on dbt-core's side. Here's the [link](https://github.com/dbt-labs/dbt-core/issues/7627) for the issue I opened on their repo, in case anyone else is interested.

Thanks!

**Comment by fivetran-joemarkiewicz** [comment] 2023-05-16 00:45
Thanks for sharing the update @antoniofranciscoandrade and glad you were able to get it working!

Will close this issue.

**Closed by fivetran-joemarkiewicz** 2023-05-16 00:45 UTC
